// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6LPc5S3_41bmMm-y98OFKItpC-f4z4U',
    appId: '1:989081396170:web:709037714fd891bca6a533',
    messagingSenderId: '989081396170',
    projectId: 'e-commerse-f6eec',
    authDomain: 'e-commerse-f6eec.firebaseapp.com',
    databaseURL: 'https://e-commerse-f6eec-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-f6eec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3A4fKm84jROpjihNeexIB4XDlmCNCnvs',
    appId: '1:989081396170:android:01dfcfff9a51e527a6a533',
    messagingSenderId: '989081396170',
    projectId: 'e-commerse-f6eec',
    databaseURL: 'https://e-commerse-f6eec-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-f6eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz8gAgCXBSRfir3iVFgU8KYfMOti9OgDY',
    appId: '1:989081396170:ios:5461abbeab3e6f97a6a533',
    messagingSenderId: '989081396170',
    projectId: 'e-commerse-f6eec',
    databaseURL: 'https://e-commerse-f6eec-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-f6eec.appspot.com',
    iosClientId: '989081396170-ahids2ab9rqtsbnkk3stg2nqnmr4c878.apps.googleusercontent.com',
    iosBundleId: 'com.example.olshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz8gAgCXBSRfir3iVFgU8KYfMOti9OgDY',
    appId: '1:989081396170:ios:5461abbeab3e6f97a6a533',
    messagingSenderId: '989081396170',
    projectId: 'e-commerse-f6eec',
    databaseURL: 'https://e-commerse-f6eec-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerse-f6eec.appspot.com',
    iosClientId: '989081396170-ahids2ab9rqtsbnkk3stg2nqnmr4c878.apps.googleusercontent.com',
    iosBundleId: 'com.example.olshop',
  );
}
